---
apiVersion: hub.traefik.io/v1alpha1
kind: APIPortal
metadata:
  name: portal
  namespace: tenant3
spec:
  title: API Portal
  description: "Developer Portal"
  trustedUrls:
    - https://portal.tenant3.dbl25tst3w18.mageekbox.eu
  ui:
    logoUrl: https://traefik.io/favicon.png